### ISSUE TITLE
FR: Allow other filetypes besides markdown

### ISSUE THREAD

**Issue by fbearoff** [yaocccc/nvim-hl-mdcodeblock.lua#1]
Filetypes other than markdown make use of fenced code blocks such as Quarto and Rmarkdown. It would be nice to have a config option to select what filetypes to apply highlighting to.

**Comment by yaocccc** [comment]
> Filetypes other than markdown make use of fenced code blocks such as Quarto and Rmarkdown. It would be nice to have a config option to select what filetypes to apply highlighting to.

yes, see it. It is the first version, I will keep upgrade it.
